### PR TITLE
Wrap special pages request in a promise

### LINKED ISSUE #41: Doesn't return 'looking  for' items
e.g. Brexit, portfolio

Recent change must've broken it @matthew-andrews

### PR DESCRIPTION
**Pull request by TheoLeanse**
@matthew-andrews @wheresrhys 

This seems to fix #41 -- we weren't waiting for the response from bertha -- but is there a nicer way to do this?

### CODE REVIEW

File: server/jobs/looking-for.js [hunk 1]
```diff
@@ -7,38 +7,40 @@ var raven = require('@financial-times/n-raven');
 var logger = require('ft-next-logger');
 
 var fetchLookingFor = function () {
-	eagerFetch('https://bertha.ig.ft.com/view/publish/gss/1rHuBdwKLGMs0azyDdyrKbLEesBbKS9TVJVPCwD83LX4/pages', {
```
Comment (wheresrhys) [inline server/jobs/looking-for.js]: you could probably just put a`return` at the start of this line instead of wrapping in a Promise as eagerFetch returns a promise.

File: server/app.js [hunk 2]
```diff
@@ -25,8 +25,8 @@ app.get('/__gtg', function(req, res) {
 });
 
 // Start polling the data
-taxonomy.init();
-lookingFor.init();
+lookingFor.init()
```
Comment (wheresrhys) [inline server/app.js]: very weird - this shouldn't matter

Comment (TheoLeanse) [inline server/app.js]: how come?

**Comment by TheoLeanse** [comment]
@wheresrhys @matthew-andrews 

ok -- passing CI now and I think ok to be merged?

File: server/jobs/taxonomy.js [hunk 3]
```diff
@@ -63,8 +59,8 @@ module.exports = {
 			});
 		}
 	},
-
+	updateTaxonomiesArray: updateTaxonomiesArray,
 	init: init
 };
 
-updateTaxonomiesArray();
+updateTaxonomiesArray([]);
```
Comment (wheresrhys) [inline server/jobs/taxonomy.js]: I think you can probably get rid of this now

**Comment by wheresrhys** [comment]
:+1:
